# Generated by Django 4.0.6 on 2022-07-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_license_number',
        ),
        migrations.AddField(
            model_name='business',
            name='business_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
