# Generated by Django 4.0.6 on 2022-07-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_business_businessimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='businessImage',
            new_name='business_image',
        ),
    ]
