# Generated by Django 4.0.6 on 2022-07-28 20:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_business_description_business_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='businessImage',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_path),
        ),
    ]
